import type { Locale } from "@/i18n/config";

type ScannerCopy = {
  intro: string;
  features: readonly string[];
  limitations: string;
  mapIntro: string;
  releaseNotes: string;
};

export const scannerCopy: Record<Locale, ScannerCopy> = {
  en: {
    intro: "Scan / Discover / Identify / Map / Diagnose / Manage",
    features: [
      "Progressive ICMP/TCP, ONVIF, mDNS and SSDP discovery with bounded concurrency, ARP/MAC evidence and offline vendor lookup",
      "Unified Network Map and virtualized device table with shared search, confidence, zoom/pan, branch controls and device details",
      "Confirmed LLDP/CDP adjacency only with your authorized SNMP credentials; inferred gateway routes remain distinct from physical links",
      "Device Control Panel for supported IPv4 IP, mask, gateway, DNS and DHCP changes through authenticated, verified-HTTPS ONVIF",
      "Collision checks, explicit confirmation, identity/configuration read-back and honest reporting of partial changes or required reboot",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Automatic adapter detection, validated IPv4 ranges and manual IPv6 targets limited to 256 addresses",
    ], limitations: "Manage only authorized devices. In-app changes require a verified HTTPS ONVIF endpoint, a stable identity and verified administrator permission. HTTP-only and proprietary vendor APIs are unsupported; credentials stay in session memory. A MAC change is not proof of conflict and silence does not prove an IP is free. Physical camera interoperability and real-network accuracy have not been measured; the binaries are unsigned.",
    mapIntro: "Two top tabs: SCAN and a full-canvas vertical NETWORK MAP. Solid links show confirmed LLDP adjacency, not direction; dashed links are inferred logical routes. Physical connections without evidence remain unknown.",
    releaseNotes: "Release notes & verified packages",
  },
  tr: {
    intro: "Tara / Keşfet / Tanı / Haritala / Tanıla / Yönet",
    features: [
      "Sınırlı eşzamanlılıkla ilerlemeli ICMP/TCP, ONVIF, mDNS ve SSDP keşfi; ARP/MAC kanıtı ve çevrimdışı üretici eşleştirmesi",
      "Ortak arama, güven düzeyi, zoom/pan, dal kontrolleri ve cihaz detaylarıyla birleşik Network Map ve sanallaştırılmış cihaz tablosu",
      "Yalnızca sizin yetkili SNMP bilgilerinizle doğrulanmış LLDP/CDP komşuluğu; çıkarımsal ağ geçidi rotaları fiziksel bağlantılardan ayrı gösterilir",
      "Kimliği doğrulanmış, sertifikası doğrulanan HTTPS ONVIF üzerinden desteklenen IPv4 IP, maske, gateway, DNS ve DHCP değişiklikleri için Cihaz Kontrol Paneli",
      "Çakışma kontrolü, açık onay, kimlik/yapılandırma doğrulaması ve kısmi değişiklik veya yeniden başlatma gereksiniminin açık bildirimi",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Otomatik adaptör algılama, doğrulanan IPv4 aralıkları ve 256 adresle sınırlı manuel IPv6 hedefleri",
    ], limitations: "Yalnızca yetkili cihazları yönetin. Uygulama içi değişiklikler doğrulanan HTTPS ONVIF, kararlı cihaz kimliği ve doğrulanan yönetici yetkisi gerektirir. HTTP-only ve üreticiye özel API'ler desteklenmez; kimlik bilgileri oturum belleğinde kalır. MAC değişimi çakışmayı, yanıt alınamaması boş IP'yi kanıtlamaz. Fiziksel kamera uyumluluğu ve gerçek ağ doğruluğu ölçülmedi; binary'ler dijital imzasızdır.",
    mapIntro: "Üstte iki sekme: SCAN ve tam alanı kullanan dikey NETWORK MAP. Düz çizgiler yönü değil, doğrulanmış LLDP/CDP komşuluğunu; kesikli çizgiler çıkarımsal mantıksal rotayı gösterir. Kanıtı olmayan fiziksel bağlantılar bilinmiyor kalır.",
    releaseNotes: "Sürüm notları ve doğrulanan paketler",
  },
  de: {
    intro: "Scannen / Erkennen / Identifizieren / Kartieren / Diagnostizieren / Verwalten",
    features: [
      "Fortlaufende ICMP/TCP-, ONVIF-, mDNS- und SSDP-Erkennung mit begrenzter Parallelität, ARP/MAC-Nachweisen und Offline-Herstellerdaten",
      "Netzwerkkarte und virtualisierte Gerätetabelle mit gemeinsamer Suche, Vertrauensstufen, Zoom und Zweigsteuerung",
      "Bestätigte LLDP-Nachbarschaft nur mit Ihren autorisierten SNMP-Daten; abgeleitete Routen sind keine physischen Verbindungen",
      "Gerätesteuerung für unterstützte IPv4-, Masken-, Gateway-, DNS- und DHCP-Änderungen über authentifiziertes ONVIF mit geprüftem HTTPS",
      "Kollisionsprüfung, ausdrückliche Bestätigung, Identitäts-/Konfigurationsprüfung und Meldung von Teiländerungen oder Neustartbedarf",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Automatische Adaptererkennung, validierte IPv4-Bereiche und manuelle IPv6-Ziele mit maximal 256 Adressen",
    ], limitations: "Nur autorisierte Geräte verwalten. Änderungen erfordern geprüftes HTTPS-ONVIF, eine stabile Identität und bestätigte Administratorrechte. Nur-HTTP-Geräte und proprietäre APIs werden nicht unterstützt; Zugangsdaten bleiben im Sitzungsspeicher. MAC-Wechsel beweisen keinen Konflikt, fehlende Antworten keine freie IP. Physische Kamera-Kompatibilität und reale Netzwerkgenauigkeit wurden nicht gemessen; die Binärdateien sind unsigniert.",
    mapIntro: "Tabelle und Knotengraph in einem Arbeitsbereich. Durchgezogene Linien bestätigen LLDP-Nachbarschaft, nicht Richtung; gestrichelte Linien sind abgeleitete logische Routen. Physische Verbindungen ohne Nachweis bleiben unbekannt.",
    releaseNotes: "Versionshinweise und geprüfte Pakete",
  },
  fr: {
    intro: "Scanner / Découvrir / Identifier / Cartographier / Diagnostiquer / Gérer",
    features: [
      "Découverte progressive ICMP/TCP, ONVIF, mDNS et SSDP à concurrence limitée, preuves ARP/MAC et fabricants hors ligne",
      "Carte réseau et table virtualisée avec recherche commune, confiance, zoom, branches et détails des appareils",
      "Voisinage LLDP confirmé uniquement avec vos identifiants SNMP autorisés ; les routes déduites ne sont pas des liens physiques",
      "Contrôle des modifications IPv4, masque, passerelle, DNS et DHCP prises en charge via ONVIF authentifié et HTTPS vérifié",
      "Vérification des collisions, confirmation explicite, relecture de l'identité/configuration et signalement des changements partiels ou redémarrages",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Détection des adaptateurs, plages IPv4 validées et cibles IPv6 manuelles limitées à 256 adresses",
    ], limitations: "Gérez seulement les appareils autorisés. Les changements exigent ONVIF HTTPS vérifié, une identité stable et des droits administrateur confirmés. HTTP seul et les API propriétaires ne sont pas pris en charge ; les identifiants restent en mémoire de session. Un changement MAC ne prouve pas un conflit, le silence ne prouve pas une IP libre. La compatibilité physique des caméras et la précision réelle n'ont pas été mesurées ; les exécutables ne sont pas signés.",
    mapIntro: "Table et graphe dans un seul espace. Les traits pleins confirment le voisinage LLDP, pas la direction ; les pointillés sont des routes logiques déduites. Les connexions physiques sans preuve restent inconnues.",
    releaseNotes: "Notes de version et paquets vérifiés",
  },
  es: {
    intro: "Escanear / Descubrir / Identificar / Mapear / Diagnosticar / Administrar",
    features: [
      "Descubrimiento progresivo ICMP/TCP, ONVIF, mDNS y SSDP con concurrencia limitada, pruebas ARP/MAC y fabricantes sin conexión",
      "Mapa de red y tabla virtualizada con búsqueda común, confianza, zoom, ramas y detalles del dispositivo",
      "Vecindad LLDP confirmada solo con tus credenciales SNMP autorizadas; las rutas inferidas no son enlaces físicos",
      "Control de cambios IPv4, máscara, puerta de enlace, DNS y DHCP compatibles mediante ONVIF autenticado y HTTPS verificado",
      "Comprobación de colisiones, confirmación explícita, verificación de identidad/configuración y avisos de cambios parciales o reinicio",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Detección de adaptadores, rangos IPv4 validados y destinos IPv6 manuales limitados a 256 direcciones",
    ], limitations: "Administra solo dispositivos autorizados. Los cambios requieren ONVIF HTTPS verificado, identidad estable y permisos de administrador confirmados. HTTP sin TLS y las API propietarias no son compatibles; las credenciales quedan en memoria de sesión. Un cambio MAC no prueba un conflicto ni el silencio una IP libre. No se midieron la compatibilidad física de cámaras ni la precisión real; los binarios no están firmados.",
    mapIntro: "Tabla y grafo en un espacio. Las líneas continuas confirman vecindad LLDP, no dirección; las discontinuas indican rutas lógicas inferidas. Las conexiones físicas sin pruebas permanecen desconocidas.",
    releaseNotes: "Notas de versión y paquetes verificados",
  },
  it: {
    intro: "Scansiona / Scopri / Identifica / Mappa / Diagnostica / Gestisci",
    features: [
      "Rilevamento progressivo ICMP/TCP, ONVIF, mDNS e SSDP con concorrenza limitata, prove ARP/MAC e produttori offline",
      "Mappa di rete e tabella virtualizzata con ricerca comune, affidabilità, zoom, rami e dettagli",
      "Adiacenza LLDP confermata solo con credenziali SNMP autorizzate; le rotte dedotte non sono collegamenti fisici",
      "Modifiche IPv4, maschera, gateway, DNS e DHCP supportate tramite ONVIF autenticato e HTTPS verificato",
      "Controllo collisioni, conferma esplicita, verifica identità/configurazione e segnalazione di modifiche parziali o riavvio",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Rilevamento adattatori, intervalli IPv4 validati e obiettivi IPv6 manuali limitati a 256 indirizzi",
    ], limitations: "Gestisci solo dispositivi autorizzati. Le modifiche richiedono HTTPS ONVIF verificato, identità stabile e permessi amministratore confermati. HTTP non protetto e API proprietarie non sono supportati; le credenziali restano nella memoria della sessione. Un cambio MAC non prova un conflitto e il silenzio non prova un IP libero. Compatibilità fisica delle telecamere e precisione reale non misurate; binari non firmati.",
    mapIntro: "Tabella e grafo in uno spazio. Le linee continue confermano adiacenza LLDP, non direzione; quelle tratteggiate sono rotte logiche dedotte. I collegamenti fisici senza prove restano sconosciuti.",
    releaseNotes: "Note di rilascio e pacchetti verificati",
  },
  pt: {
    intro: "Analisar / Descobrir / Identificar / Mapear / Diagnosticar / Gerir",
    features: [
      "Descoberta progressiva ICMP/TCP, ONVIF, mDNS e SSDP com concorrência limitada, provas ARP/MAC e fabricantes offline",
      "Mapa de rede e tabela virtualizada com pesquisa comum, confiança, zoom, ramos e detalhes",
      "Vizinhança LLDP confirmada apenas com credenciais SNMP autorizadas; rotas inferidas não são ligações físicas",
      "Alterações IPv4, máscara, gateway, DNS e DHCP suportadas por ONVIF autenticado e HTTPS verificado",
      "Verificação de colisões, confirmação explícita, validação de identidade/configuração e avisos de alterações parciais ou reinício",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Deteção de adaptadores, intervalos IPv4 validados e destinos IPv6 manuais limitados a 256 endereços",
    ], limitations: "Gira apenas dispositivos autorizados. As alterações exigem HTTPS ONVIF verificado, identidade estável e permissões de administrador confirmadas. HTTP sem TLS e APIs proprietárias não são suportados; credenciais apenas na memória da sessão. Uma mudança MAC não prova um conflito, nem o silêncio um IP livre. Compatibilidade física das câmaras e precisão real não medidas; binários sem assinatura.",
    mapIntro: "Tabela e grafo num espaço. Linhas contínuas confirmam vizinhança LLDP, não direção; linhas tracejadas são rotas lógicas inferidas. Ligações físicas sem provas ficam desconhecidas.",
    releaseNotes: "Notas da versão e pacotes verificados",
  },
  nl: {
    intro: "Scannen / Ontdekken / Identificeren / In kaart brengen / Diagnosticeren / Beheren",
    features: [
      "Progressieve ICMP/TCP-, ONVIF-, mDNS- en SSDP-detectie met begrensde gelijktijdigheid, ARP/MAC-bewijs en offline fabrikanten",
      "Netwerkkaart en gevirtualiseerde tabel met gedeelde zoekfunctie, betrouwbaarheid, zoom, takken en apparaatdetails",
      "Bevestigde LLDP-nabijheid alleen met jouw bevoegde SNMP-gegevens; afgeleide routes zijn geen fysieke verbindingen",
      "Ondersteunde IPv4-, masker-, gateway-, DNS- en DHCP-wijzigingen via geauthenticeerde ONVIF met gecontroleerde HTTPS",
      "Botsingscontrole, expliciete bevestiging, identiteits-/configuratiecontrole en meldingen van gedeeltelijke wijzigingen of herstart",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Adapterdetectie, gevalideerde IPv4-bereiken en handmatige IPv6-doelen beperkt tot 256 adressen",
    ], limitations: "Beheer alleen bevoegde apparaten. Wijzigingen vereisen gecontroleerde HTTPS-ONVIF, stabiele identiteit en bevestigde beheerdersrechten. Alleen HTTP en eigen leveranciers-API's worden niet ondersteund; inloggegevens blijven in sessiegeheugen. MAC-wijzigingen bewijzen geen conflict, stilte geen vrij IP. Fysieke cameracompatibiliteit en echte nauwkeurigheid zijn niet gemeten; bestanden zijn niet ondertekend.",
    mapIntro: "Tabel en graaf in één werkruimte. Volle lijnen bevestigen LLDP-nabijheid, niet richting; stippellijnen zijn afgeleide logische routes. Fysieke verbindingen zonder bewijs blijven onbekend.",
    releaseNotes: "Releaseopmerkingen en gecontroleerde pakketten",
  },
  pl: {
    intro: "Skanuj / Odkrywaj / Identyfikuj / Mapuj / Diagnozuj / Zarządzaj",
    features: [
      "Stopniowe wykrywanie ICMP/TCP, ONVIF, mDNS i SSDP z ograniczoną współbieżnością, dowodami ARP/MAC i lokalną bazą producentów",
      "Mapa sieci i wirtualizowana tabela ze wspólnym wyszukiwaniem, poziomem pewności, zoomem, gałęziami i szczegółami",
      "Potwierdzone sąsiedztwo LLDP tylko z autoryzowanymi danymi SNMP; wywnioskowane trasy nie są fizycznymi połączeniami",
      "Obsługiwane zmiany IPv4, maski, bramy, DNS i DHCP przez uwierzytelnione ONVIF ze zweryfikowanym HTTPS",
      "Sprawdzenie kolizji, jawne potwierdzenie, weryfikacja tożsamości/konfiguracji i raport częściowych zmian lub potrzeby restartu",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Wykrywanie kart, walidowane zakresy IPv4 i ręczne cele IPv6 ograniczone do 256 adresów",
    ], limitations: "Zarządzaj tylko autoryzowanymi urządzeniami. Zmiany wymagają zweryfikowanego HTTPS ONVIF, stabilnej tożsamości i potwierdzonych uprawnień administratora. HTTP bez TLS i własne API producentów nie są obsługiwane; dane logowania pozostają w pamięci sesji. Zmiana MAC nie dowodzi konfliktu, a brak odpowiedzi wolnego IP. Zgodność fizycznych kamer i rzeczywista dokładność nie zostały zmierzone; pliki nie są podpisane.",
    mapIntro: "Tabela i graf w jednym obszarze. Linie ciągłe potwierdzają sąsiedztwo LLDP, nie kierunek; przerywane oznaczają wywnioskowane trasy logiczne. Fizyczne połączenia bez dowodów pozostają nieznane.",
    releaseNotes: "Informacje o wydaniu i zweryfikowane pakiety",
  },
  ru: {
    intro: "Сканировать / Обнаруживать / Определять / Картировать / Диагностировать / Управлять",
    features: [
      "Постепенное обнаружение ICMP/TCP, ONVIF, mDNS и SSDP с ограниченной параллельностью, данными ARP/MAC и локальной базой производителей",
      "Карта сети и виртуализированная таблица с общим поиском, уверенностью, масштабированием, ветвями и подробностями",
      "Подтверждённое соседство LLDP только с вашими разрешёнными данными SNMP; предполагаемые маршруты не являются физическими связями",
      "Поддерживаемые изменения IPv4, маски, шлюза, DNS и DHCP через аутентифицированный ONVIF с проверенным HTTPS",
      "Проверка коллизий, явное подтверждение, проверка идентичности/настроек и сообщения о частичных изменениях или перезагрузке",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "Определение адаптеров, проверенные диапазоны IPv4 и ручные цели IPv6 до 256 адресов",
    ], limitations: "Управляйте только разрешёнными устройствами. Изменения требуют проверенного HTTPS ONVIF, стабильной идентичности и подтверждённых прав администратора. HTTP без TLS и фирменные API не поддерживаются; учётные данные остаются в памяти сеанса. Изменение MAC не доказывает конфликт, отсутствие ответа — свободный IP. Совместимость физических камер и реальная точность не измерены; файлы не подписаны.",
    mapIntro: "Таблица и граф в одном пространстве. Сплошные линии подтверждают соседство LLDP, но не направление; пунктирные — предполагаемые логические маршруты. Физические связи без доказательств остаются неизвестными.",
    releaseNotes: "Примечания к выпуску и проверенные пакеты",
  },
  ar: {
    intro: "فحص / اكتشاف / تحديد / رسم / تشخيص / إدارة",
    features: [
      "اكتشاف تدريجي عبر ICMP/TCP وONVIF وmDNS وSSDP بتزامن محدود وأدلة ARP/MAC وقاعدة مصنعين محلية",
      "خريطة شبكة وجدول أجهزة افتراضي ببحث مشترك ومستويات ثقة وتكبير وفروع وتفاصيل",
      "جوار LLDP مؤكد فقط ببيانات SNMP المصرح بها؛ المسارات المستنتجة ليست وصلات مادية",
      "تغييرات IPv4 والقناع والبوابة وDNS وDHCP المدعومة عبر ONVIF موثق وHTTPS متحقق",
      "فحص التعارض والتأكيد الصريح والتحقق من الهوية والإعدادات والإبلاغ عن التغييرات الجزئية أو الحاجة لإعادة التشغيل",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "اكتشاف المحولات والتحقق من نطاقات IPv4 وأهداف IPv6 يدوية بحد 256 عنواناً",
    ], limitations: "أدر الأجهزة المصرح بها فقط. التغييرات تتطلب HTTPS ONVIF متحققاً وهوية ثابتة وصلاحية مدير مؤكدة. HTTP دون TLS وواجهات المصنع الخاصة غير مدعومة؛ تبقى بيانات الدخول في ذاكرة الجلسة. تغيير MAC لا يثبت تعارضاً وعدم الرد لا يثبت أن IP متاح. لم يُقَس توافق الكاميرات الفعلية أو دقة الشبكة الواقعية؛ الملفات غير موقعة رقمياً.",
    mapIntro: "الجدول والرسم في مساحة واحدة. الخطوط المتصلة تؤكد جوار LLDP وليس الاتجاه؛ المتقطعة مسارات منطقية مستنتجة. الوصلات المادية بلا دليل تبقى مجهولة.",
    releaseNotes: "ملاحظات الإصدار والحزم المتحققة",
  },
  ja: {
    intro: "スキャン / 検出 / 識別 / マップ / 診断 / 管理",
    features: [
      "並列数を制限した ICMP/TCP、ONVIF、mDNS、SSDP の逐次結果表示、ARP/MAC 証拠とオフラインメーカー検索",
      "共通検索、信頼度、ズーム、分岐操作、詳細を備えたネットワークマップと仮想化デバイス表",
      "許可された SNMP 認証情報による LLDP 隣接確認のみ。推定ルートと物理接続は区別",
      "認証済み・HTTPS 検証済み ONVIF による対応 IPv4、マスク、ゲートウェイ、DNS、DHCP 設定変更",
      "競合確認、明示的承認、識別情報・設定の再確認、部分変更や再起動の必要性を明示",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "アダプター自動検出、IPv4 範囲検証、256 アドレスまでの手動 IPv6 対象",
    ], limitations: "管理権限のある機器のみを操作してください。変更には検証済み HTTPS ONVIF、安定した識別情報、確認済み管理者権限が必要です。HTTP のみや独自 API は非対応で、認証情報はセッションメモリにのみ保持します。MAC 変更は競合の証明ではなく、無応答は未使用 IP の証明ではありません。実機カメラ互換性と実ネットワーク精度は未測定で、実行ファイルは未署名です。",
    mapIntro: "表とグラフを一つの画面に。実線は方向ではなく LLDP 隣接の確認、破線は推定論理ルートです。証拠のない物理接続は不明のままです。",
    releaseNotes: "リリースノートと検証済みパッケージ",
  },
  ko: {
    intro: "스캔 / 탐색 / 식별 / 매핑 / 진단 / 관리",
    features: [
      "제한된 동시성으로 ICMP/TCP, ONVIF, mDNS, SSDP 결과를 순차 표시하고 ARP/MAC 증거와 오프라인 제조사 조회 제공",
      "공통 검색, 신뢰도, 확대, 분기 제어, 상세 정보를 갖춘 네트워크 맵과 가상화 장치 표",
      "승인된 SNMP 자격 증명으로 확인된 LLDP 인접 관계만 표시하며 추론 경로와 물리 연결을 구분",
      "인증 및 HTTPS 검증된 ONVIF를 통한 지원 IPv4, 마스크, 게이트웨이, DNS, DHCP 변경",
      "충돌 검사, 명시적 확인, 장치 식별·설정 재검증과 부분 변경 또는 재시작 필요 알림",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "자동 어댑터 탐지, IPv4 범위 검증 및 256개 주소로 제한된 수동 IPv6 대상",
    ], limitations: "권한이 있는 장치만 관리하세요. 변경에는 검증된 HTTPS ONVIF, 안정적인 식별 정보, 확인된 관리자 권한이 필요합니다. HTTP 전용 및 제조사 독자 API는 지원하지 않으며 자격 증명은 세션 메모리에만 보관합니다. MAC 변경은 충돌 증명이 아니고 무응답은 빈 IP 증명이 아닙니다. 실제 카메라 호환성과 실제 네트워크 정확도는 측정되지 않았으며 실행 파일은 서명되지 않았습니다.",
    mapIntro: "표와 그래프를 하나의 작업 공간으로 제공합니다. 실선은 방향이 아닌 LLDP 인접 관계 확인, 점선은 추론된 논리 경로입니다. 증거 없는 물리 연결은 알 수 없음으로 남습니다.",
    releaseNotes: "릴리스 정보 및 검증된 패키지",
  },
  zh: {
    intro: "扫描 / 发现 / 识别 / 映射 / 诊断 / 管理",
    features: [
      "限制并发的 ICMP/TCP、ONVIF、mDNS、SSDP 渐进发现，提供 ARP/MAC 证据和离线厂商查询",
      "统一网络地图与虚拟化设备表，共享搜索、置信度、缩放、分支控制和设备详情",
      "仅通过授权 SNMP 凭据确认 LLDP 邻接；推断路由与物理连接分别标记",
      "通过已认证且 HTTPS 已验证的 ONVIF 修改支持的 IPv4、掩码、网关、DNS 和 DHCP",
      "冲突检查、明确确认、身份与配置回读，并如实报告部分更改或重启需求",
      "CSV / JSON / HTML reports · SVG / PNG Network Map",
      "自动适配器检测、IPv4 范围验证，以及最多 256 个地址的手动 IPv6 目标",
    ], limitations: "仅管理获授权的设备。更改需要已验证的 HTTPS ONVIF、稳定身份和确认的管理员权限。不支持纯 HTTP 和厂商专有 API；凭据仅保存在会话内存中。MAC 更改不能证明冲突，无响应不能证明 IP 空闲。尚未测量实体摄像机兼容性和真实网络准确率；可执行文件未签名。",
    mapIntro: "设备表与节点图在同一工作区。实线表示已确认的 LLDP 邻接而非方向；虚线表示推断的逻辑路由。没有证据的物理连接保持未知。",
    releaseNotes: "发行说明与已验证软件包",
  },
};
