<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IPCast.Network</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IPCast.Shared\IPCast.Shared.csproj" />
  </ItemGroup>

</Project>
